<?php

namespace Database\Seeders;

use App\Models\Invoice;
use App\Models\Order;
use App\Models\OrderSizeDetail;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;

class DummyDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $admin = User::where('role', 'admin')->first() ?? User::factory()->create(['role' => 'admin']);
        
        $customers = ['PT. Maju Jaya', 'CV. Sablon Kreatif', 'Toko Baju Laris', 'Universitas Nasional', 'BEM Universitas Merdeka', 'PT. Tekstil Indah', 'Dinas Pendidikan Kota', 'Komunitas Motor Gede', 'SMA 1 Negeri', 'Startup Tech Nusantara'];
        $productTypes = ['Kaos (T-Shirts)', 'Pakaian Denim', 'Pakaian Olahraga', 'Seragam PDH/PDL', 'Kemeja Formal', 'Jaket Bomber', 'Topi Custom'];
        $statuses = ['order_received', 'fabric_cutting', 'sewing', 'embroidery', 'button_installation', 'shipping'];

        // Generate 500 orders over the last 5 years
        for ($i = 1; $i <= 500; $i++) {
            // Random date within the last 5 years (1825 days)
            $createdDate = Carbon::now()->subDays(rand(1, 1825))->startOfDay()->addHours(rand(8, 17));
            
            // If the order is older than 60 days, it is almost certainly completed
            $daysSinceCreated = Carbon::now()->diffInDays($createdDate);
            $isCompleted = $daysSinceCreated > 60 ? true : (rand(1, 10) > 4); // If new, 60% completed
            $status = $isCompleted ? 'shipping' : $statuses[array_rand(array_slice($statuses, 0, 5))];

            $order = Order::create([
                'created_by' => $admin->id,
                'order_number' => 'ORD-' . $createdDate->format('Y') . '-' . str_pad($i, 4, '0', STR_PAD_LEFT),
                'customer_name' => $customers[array_rand($customers)],
                'customer_phone' => '08' . rand(1000000000, 9999999999),
                'customer_category' => rand(1, 10) > 3 ? 'b2b' : 'retail', // 70% B2B, 30% Retail
                'product_name' => 'Custom ' . $productTypes[array_rand($productTypes)],
                'product_type' => $productTypes[array_rand($productTypes)],
                'color' => ['Navy Blue', 'Maroon', 'Hitam', 'Putih', 'Abu-abu', 'Hijau Army'][rand(0, 5)],
                'total_price' => 0, // Will update later
                'total_cost' => 0, // Will update later
                'order_date' => $createdDate->toDateString(),
                'deadline' => $createdDate->copy()->addDays(rand(14, 45))->toDateString(),
                'current_status' => $status,
                'notes' => 'Generated by DummyDataSeeder for 5-year history.',
                'created_at' => $createdDate,
                'updated_at' => $isCompleted ? $createdDate->copy()->addDays(rand(10, 40)) : $createdDate->copy()->addDays(rand(1, 5)),
                'archived_at' => $isCompleted ? $createdDate->copy()->addDays(rand(45, 60)) : null,
            ]);

            $totalQty = 0;
            $totalPrice = 0;
            
            // Generate Size Details
            $sizes = ['S', 'M', 'L', 'XL', 'XXL'];
            $selectedSizes = (array) array_rand(array_flip($sizes), rand(1, 4));
            $gender = ['male', 'female', 'child'][rand(0, 2)];
            
            foreach ($selectedSizes as $size) {
                // If B2B, quantity is higher
                $qty = $order->customer_category === 'b2b' ? rand(50, 500) : rand(5, 30);
                $price = rand(50, 150) * 1000; // 50k to 150k
                
                OrderSizeDetail::create([
                    'order_id' => $order->id,
                    'gender' => $gender,
                    'size' => $size,
                    'quantity' => $qty,
                    'price' => $price,
                ]);
                
                $totalQty += $qty;
                $totalPrice += ($qty * $price);
            }

            // Estimate total cost (profit margin 20% - 40%)
            $margin = rand(20, 40) / 100;
            $totalCost = $totalPrice * (1 - $margin);

            // Update Order total
            $order->update([
                'total_price' => $totalPrice,
                'total_cost' => $totalCost,
            ]);

            // Create Invoice
            Invoice::create([
                'order_id' => $order->id,
                'invoice_number' => 'INV-' . strtoupper(Str::random(6)),
                'subtotal' => $totalPrice,
                'grand_total' => $totalPrice,
                'paid_amount' => $isCompleted ? $totalPrice : (rand(0, 1) ? $totalPrice : 0),
                'payment_status' => $isCompleted ? 'paid' : (rand(0, 1) ? 'paid' : 'unpaid'),
                'created_at' => $createdDate,
                'updated_at' => $createdDate,
            ]);
            
            // Generate some random tracking history to make it look real
            $order->trackingHistories()->create([
                'status' => 'order_received',
                'description' => 'Pesanan diterima.',
                'updated_by' => $admin->id,
                'created_at' => $createdDate,
            ]);
            
            if ($isCompleted) {
                $order->trackingHistories()->create([
                    'status' => 'shipping',
                    'description' => 'Pesanan selesai dan dikirim.',
                    'updated_by' => $admin->id,
                    'created_at' => $order->updated_at,
                ]);
            }
        }
    }
}
